<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/12/18
 * Time: 14:18
 */

namespace common\base;

use common\helpers\WeHelper;
use yii\rest\ActiveController;
use yii\helpers\Json;
class RController extends ActiveController
{
    public $modelClass = 'backend\models\Admin';

    public $except_token = ['login'];

    public function beforeAction($action)
    {
        /*token检查*/
        if (!in_array($action->id, $this->except_token)) {
            $service = $this->getService('Admins.Admin');
            $res = $service->checkToken();
            if (is_array($res)) {
                echo Json::encode($res);
                exit();
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /**
     * 获取服务接口
     * @param $servName
     * @return object
     */
    protected function getService($servName, $proxied = false)
    {
        header("Access-Control-Allow-Origin: *");
        $serv = WeHelper::getService($servName);
        if ($proxied) {
            $servProxy = new ServiceProxy($serv, $this->view);
            $serv = $servProxy;
        }
        return $serv;
    }
}