<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/12/18
 * Time: 18:17
 */

namespace backend\modules\product\controllers;

use common\base\RController;
use yii\helpers\Json;

class CategoryController extends RController
{
    public $modelClass = 'backend\models\Category';

    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $service = $this->getService('Products.Category');
        $res = $service->getList();
        echo Json::encode($res);
        exit();
    }

    public function actionView()
    {
        $service = $this->getService('Products.Category');
        $res = $service->view();
        echo Json::encode($res);
        exit();
    }

    public function actionCreate()
    {
        $service = $this->getService('Products.Category');
        $res = $service->create();
        echo Json::encode($res);
        exit();
    }

    public function actionUpdate()
    {
        $service = $this->getService('Products.Category');
        $res = $service->update();
        echo Json::encode($res);
        exit();
    }

    public function actionDelete()
    {
        $service = $this->getService('Products.Category');
        $res = $service->delete();
        echo Json::encode($res);
        exit();
    }

    public function actionShow()
    {
        $service = $this->getService('Products.Category');
        $res = $service->show();
        echo Json::encode($res);
        exit();
    }

}