<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/12/18
 * Time: 18:17
 */

namespace backend\modules\coupon\controllers;

use common\base\RController;
use common\helpers\BackendErrorCode;
use common\helpers\WeHelper;
use yii\helpers\Json;

class CouponController extends RController
{

    /*检查数据冻结的路由*/
    public $check_lock_route = ['update', 'giveout'];


    public $modelClass = 'backend\models\Coupon';

    public function actions()
    {
        $action = parent::actions();
        unset($action['index']);
        unset($action['update']);
        unset($action['create']);
        unset($action['delete']);
        return $action;
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        if (in_array($action->id,$this->check_lock_route)){
            $service = $this->getService('Coupon.Coupon');
            $res = $service->checkLock();
            if ($res===false) {
                header("Content-Type:application/json;charset=UTF-8");
                echo json_encode(WeHelper::jsonReturn(null, BackendErrorCode::ERR_LOCK), JSON_UNESCAPED_UNICODE);
                die();
            }
        }
        return true;
    }

    /**
     * 获取优惠券列表
     * @return mixed
     */
    public function actionIndex()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->getList();
    }

    /**
     * 查看优惠券详情
     * @return mixed
     */
    public function actionView()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->view();
    }

    /**
     * 新增优惠券
     * @return mixed
     */
    public function actionCreate()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->create();
    }

    /**
     * 修改优惠券
     * @return mixed
     */
    public function actionUpdate()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->update();
    }

    /**
     * 删除优惠券
     * @return mixed
     */
    public function actionDelete()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->delete();
    }

    /**
     * 冻结或解冻优惠券
     * @return mixed
     */
    public function actionLock()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->lockCouponById();
    }

    /**
     * 发放优惠券
     * @return mixed
     */
    public function actionGiveout()
    {
        $service = $this->getService('Coupon.Coupon');
        return $service->giveout();
    }

}