<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/12/18
 * Time: 18:17
 */

namespace backend\modules\coupon\controllers;

use common\base\RController;
use common\helpers\BackendErrorCode;
use common\helpers\WeHelper;
use yii\helpers\Json;

class UserCouponController  extends RController
{
    public $modelClass='backend\models\UserCoupon';

    /*检查数据冻结的路由*/
    public $check_lock_route = ['update'];

    /**
     * @return array
     */
    public function actions()
    {
        return [];
    }


    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        if (in_array($action->id,$this->check_lock_route)){
            $service = $this->getService('Coupon.UserCoupon');
            $res = $service->checkLock();
            if ($res===false) {
                header("Content-Type:application/json;charset=UTF-8");
                echo json_encode(WeHelper::jsonReturn(null, BackendErrorCode::ERR_LOCK), JSON_UNESCAPED_UNICODE);
                die();
            }
        }
        return true;
    }

    /**
     * 获取用户优惠券列表
     * @return mixed
     */
    public function actionIndex()
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->getUserList();
    }

    /**
     * 获取用户优惠券详情
     * @return mixed
     */
    public function actionView($id)
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->getView($id);
    }

    /**
     * 添加用户优惠券
     * @return mixed
     */
    public function actionCreate()
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->create();
    }

    /**
     * 修改用户优惠券
     * @return mixed
     */
    public function actionUpdate()
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->update();
    }

    /**
     * 删除用户优惠券
     * @return mixed
     */
    public function actionDelete()
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->delete();
    }

    /**
     * 冻结|解冻用户优惠券
     * @return mixed
     */
    public function actionLock()
    {
        $service = $this->getService('Coupon.UserCoupon');
        return $service->lock();
    }

}