<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/12/18
 * Time: 18:17
 */

namespace backend\modules\ad\controllers;

use common\base\RController;
use common\helpers\BackendErrorCode;
use common\helpers\WeHelper;

class BannerController extends RController
{
    public $modelClass= 'backend\models\Banner';

    /*检查数据冻结的路由*/
    public $check_lock_route = ['update'];

    public function actions()
    {
        return [];
    }


    public function beforeAction($action)
    {
        parent::beforeAction($action); // TODO: Change the autogenerated stub
        if (in_array($action->id,$this->check_lock_route)){
            $service = $this->getService('Ad.Banner');
            $res = $service->checkLock();
            if ($res===false) {
                header("Content-Type:application/json;charset=UTF-8");
                echo json_encode(WeHelper::jsonReturn(null, BackendErrorCode::ERR_LOCK), JSON_UNESCAPED_UNICODE);
                die();
            }
        }
        return true;
    }

    /**
     * 广告列表
     * @return mixed
     */
    public function actionIndex()
    {

        $service = $this->getService('Ad.Banner');
        return $service->getList();
    }

    /**
     * 广告详情
     * @return mixed
     */
    public function actionView()
    {
        $service = $this->getService('Ad.Banner');
        return $service->view();
    }

    /**
     * 创建广告
     * @return mixed
     */
    public function actionCreate()
    {
        $service = $this->getService('Ad.Banner');
        return $service->create();
    }

    /**
     * 修改广告
     * @return mixed
     */
    public function actionUpdate()
    {
        $service = $this->getService('Ad.Banner');
        return $service->update();
    }

    /**
     * 删除广告
     * @return mixed
     */
    public function actionDelete()
    {
        $service = $this->getService('Ad.Banner');
        return $service->delete();
    }

    /**
     *  广告冻结|解冻
     * @return mixed
     */
    public function actionLock()
    {
        $service = $this->getService('Ad.Banner');
        return $service->lock();
    }

}