<?php

namespace app\modules\v1\site\controllers;

use app\controllers\RController;

/**
 * Created by von.
 * User: FOCUS
 * Date: 2019/1/23
 * Time: 14:54
 */
class SiteController extends RController
{
    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * 获取分类模块信息
     * @return mixed
     * @author von
     */
    public function actionCategoryRelease()
    {
        $service = $this->getService('Product.CategoryRelease');
        return $service->getAppCategoryRelease();
    }

    /**
     * 获取app的广告
     * @return mixed
     * @author von
     */
    public function actionBanners()
    {
        $service = $this->getService('Ad.Ad');
        return $service->getAppBanners();
    }

    /**
     * 获取菜单
     * @return mixed
     * @author von
     */
    public function actionNav()
    {
        $service = $this->getService('Rbac.Nav');
        return $service->getAppNav();
    }
}