<?php
/**
 * Created by von.
 * User: FOCUS
 * Date: 2019/1/9
 * Time: 11:21
 */

namespace backend\modules\rbac\controllers;

use common\base\RController;

class AuthController extends RController
{
    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * 权限列表
     * @return mixed 
     * @author von
     */
    public function actionIndex()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->getList();
    }

    /**
     * 创建权限
     * @return mixed
     */
    public function actionCreate()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->create();

    }

    /**
     * 修改权限
     * @return mixed
     */
    public function actionUpdate()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->update();
    }

    /**
     * 删除权限
     * @return mixed
     */
    public function actionDelete()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->delete();
    }

    /**
     * 权限冻结
     * @return mixed
     */
    public function actionLock()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->lock();
    }

    /**
     * 获取树型
     * @return mixed
     */
    public function actionTree()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->getAuthTree();
    }

    /**
     * 获取权限集 给角色添加使用
     * @return mixed
     */
    public function actionCheckbox ()
    {
        $service = $this->getService('Rbac.Auth');
        return $service->checkbox();
    }

}