<?php
/**
 **********************************************************
 * @author : YiChaobao [ yichaobao@163.com ]
 * @time : 2019/01/01 00:00
 * @copyright : (c) 2019 YiChaobao All rights reserved.
 **********************************************************
 * @name : AreaController.php
 * @description : 地区模块
 **/
namespace backend\modules\area\controllers;
use common\base\RController;
use Yii;
class AreaController extends RController
{
    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }
    public function actionIndex()
    {
        $service = $this->getService('Basic.Area');
        return $service->getAllData();
    }
}