<?php

namespace backend\models;

use common\helpers\ConstantHelper;
use common\helpers\Param;
use Yii;

/**
 * This is the model class for table "{{%ad}}".
 *
 * @property int $id
 * @property int type
 * @property string $ad_name
 * @property string mark
 * @property string $source
 * @property int max_number
 * @property int size
 * @property int is_show
 * @property int display_order
 * @property int $is_delete
 * @property int $created_at
 * @property int $updated_at
 */
class Ad extends BaseModel
{

    const SOURCE_XCX = 1;
    const SOURCE_IOS = 2;
    const SOURCE_AND = 3;

    /**
     * 翻译source字段
     * @param string $key
     * @return array|mixed
     */
    public function getSourceItem($key = '')
    {
        $array = [
            1 => '小程序',
            2 => 'ios',
            3 => 'android',
        ];
        if (empty(!$key)) {
            return $array[$key];
        }
        return $array;
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%ad}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['ad_name', 'source','type','size'], 'required'],
            [['is_delete', 'created_at', 'updated_at'], 'integer'],
            [['ad_name'], 'string', 'max' => 50],
            ['max_number', 'default', 'value' => 1],
            ['display_order', 'default', 'value' => 0],
            ['source', 'in', 'range' => ['weixin', 'ios', 'android'],'message'=>'范围值:\'weixin\', \'ios\', \'android\''],
//          ['ad_name', 'checkUnique'],
            ['size', 'checkFormat'],
            [['mark', 'type', 'source', 'max_number', 'size', 'is_show', 'display_order'], 'safe']
        ];
    }

    /**
     * rules 验证唯一字段
     * @param $attribute
     * @param $param
     */
    public function checkUnique($attribute, $param)
    {
        $model = $this->findOneByBannerName($this->$attribute);
        if ($model) {
            if ($model->id != $this->id && $model->is_delete == self::DELETE_NOT) {
                $this->addError($attribute, $this->$attribute . '已存在');
            }
        }
    }

    /**
     * rules 验证size的正则
     * @param $attribute
     * @param $param
     */
    public function checkFormat($attribute, $param)
    {
        $r='/\d+([.]?\d)*\*\d+([.]?\d)*/';
        if (!preg_match($r,$this->$attribute)) {
            $this->addError($attribute,'参照格式:200*300');
        }
    }

    /**
     * @return array
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(),
            [
//                'update' => ['ad_name', 'source','type','max_number'],
                'delete' => ['is_delete'],
                'show' => ['is_show'],
            ]); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ad_name' => '渠道名',
            'source' => '来源渠道',
            'size' => '尺寸（宽,高）',
            'is_delete' => 'Is Delete',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    /**
     * 通过id查询一条数据
     * @param $id
     * @return bool|null|static
     */
    public function findOneById($id)
    {
        $model = self::findOne(['id' => $id]);
        if ($model) {
            return $model;
        }
        return false;
    }

    /**
     * 通过ad_name 查询一条数据
     * @param $ad_name
     * @return bool|null|static
     */
    public function findOneByBannerName($ad_name)
    {
        $model = self::findOne(['ad_name' => $ad_name]);
        if ($model) {
            return $model;
        }
        return false;
    }

    /**
     * 处理返回的数据格式
     * @return array
     */
    public function getView()
    {
        return [
            'id' => $this->id,
            'ad_name' => $this->ad_name,
            'mark' => $this->mark,
            'type' => $this->type,
            'source' => $this->source,
            'is_show' => $this->is_show,
            'max_number' => $this->max_number,
            'display_order' => $this->display_order,
            'size' => $this->size,
            'updated_at' => $this->updated_at,
            'created_at' => $this->created_at,
        ];
    }


    /**
     * 新增一条广告渠道
     * @param $data
     * @return array|bool
     */
    public function createAd($data)
    {
        $model = new self();
        $model->attributes = $data;
        if ($model->validate() && $model->save()) {
            return true;
        }
        return $model->getErrors();
    }

    /**
     * 保存前处理数据
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->is_show = ConstantHelper::AD_IS_SHOW_TRUE;
            $this->mark = Yii::$app->security->generateRandomString(32);
            $this->is_delete = self::DELETE_NOT;
            $this->created_at = time();
            $this->updated_at = time();
        } else {
            $this->updated_at = time();
        }
        return parent::beforeSave($insert);
    }

    /**
     * 查询sql
     * @param $params
     * @return $this
     */
    public function getQuery($params)
    {
        return $query = self::find()
            ->where(['is_delete' => self::DELETE_NOT])
            ->andFilterWhere(['like', 'ad_name', $params['ad_name']])
            ->andFilterWhere(['like','source', $params['source']])
            ->andFilterWhere(['like','size', $params['size']])
            ->andFilterWhere(['type' => $params['type']])
            ;
    }

    /**
     * 修改广告渠道
     * @param $params
     * @return array|bool
     */
    public function modifyAd($params)
    {
//        $this->scenario = 'update';
        $this->attributes = $params;
        if ($this->save()) {
            return true;
        }
        return $this->getErrors();
    }


    /**
     * 获取数据列
     * @param $params
     * @return array
     */
    public function getList($params)
    {
        $page_size = Param::getHeaders('page_size');
        $page = Param::getHeaders('page');
        $query = self::getQuery($params);
        $models = $query->limit($page_size)
            ->offset(($page - 1) * $page_size)
            ->orderBy('created_at DESC')
            ->all();
        $list = [];
        foreach ($models as $model) {
            $list[] = $model->getView();
        }
        $count = $query->count();
        $param[ConstantHelper::COUNT] = $count;
        $param[ConstantHelper::PAGE] = $page;
        $param[ConstantHelper::PAGE_SIZE] = $page_size;
        $param[ConstantHelper::PAGE_COUNT] = ceil($count / $page_size);
        $param[ConstantHelper::LISTS] = $list;
        return self::backListFormat($param);
    }

    /**
     * 删除广告渠道
     * @return array|bool
     */
    public function del()
    {
        $this->scenario = 'delete';
        $this->is_delete = self::DELETED;
        /*有广告则此条数据不允许删除*/
        $bi = Banner0::find()
            ->where(['is_delete' => self::DELETE_NOT])
            ->andWhere(['id' => $this->id])
//            ->andWhere(['>', 'end_time', time()])
            ->one();
        if ($bi != null) {
            return false;
        }
        if ($this->save()) {
            return true;
        }
        return $this->getErrors();
    }

    /**
     *  广告渠道显示与隐藏
     * @return array|bool
     */
    public function showById()
    {
        $this->scenario = 'show';
        if ($this->is_show == ConstantHelper::AD_IS_SHOW_TRUE) {
            $this->is_show=ConstantHelper::AD_IS_SHOW_FALSE;
        }else{
            $this->is_show=ConstantHelper::AD_IS_SHOW_TRUE;
        }
        if ($this->save()) {
            return true;
        }
        return $this->getErrors();
    }

    /**
     * 与广告表的对应关系
     * @return \yii\db\ActiveQuery
     */
    public function getBanner()
    {
        return $this->hasMany(Banner0::className(), ['banner_id' => 'id']);
    }
}
