<?php
/**
 * Created by PhpStorm.
 * User: FOCUS
 * Date: 2018/12/19
 * Time: 16:44
 */

namespace backend\models;

use common\helpers\ConstantHelper;
use yii\db\ActiveRecord;

class BaseModel extends ActiveRecord
{

    const DELETE_NOT = 0;
    const DELETED = 1;

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param $param
     * @return mixed
     * @author von
     */
    public static function backListFormat($param)
    {
        /**数据总量**/
        $array[ConstantHelper::COUNT] = !empty($param[ConstantHelper::COUNT]) ? $param[ConstantHelper::COUNT] : 0;
        /**当前页码**/
//        $array[ConstantHelper::PAGE] = !empty($param[ConstantHelper::PAGE]) ? $param[ConstantHelper::PAGE] : 0;
        /**单页数据量**/
//        $array[ConstantHelper::PAGE_SIZE] = !empty($param[ConstantHelper::PAGE_SIZE]) ? $param[ConstantHelper::PAGE_SIZE] : \Yii::$app->params[ConstantHelper::PAGE_SIZE];
        /**分页数**/
//        $array[ConstantHelper::PAGE_COUNT] = !empty($param[ConstantHelper::PAGE_COUNT]) ? $param[ConstantHelper::PAGE_COUNT] : 0;
        /**请求数据**/
        $array[ConstantHelper::LISTS] = !empty($param[ConstantHelper::LISTS]) ? $param[ConstantHelper::LISTS] : [];
        return $array;
    }

}