<?php

namespace backend\models;

use common\helpers\ConstantHelper;
use Yii;
use common\helpers\Param;

/**
 * This is the model class for table "{{%coupon}}".
 * @property int $id
 * @property int $type
 * @property string $coupon_name
 * @property double $restriction
 * @property double $coupon_value
 * @property int $is_lock
 * @property int $is_delete
 * @property int $number
 * @property int $max_get_number
 * @property string $start_time
 * @property string $end_time
 * @property string $consume_time
 * @property string $invalid_time
 * @property int $created_at
 * @property int $updated_at
 */
class Coupon extends \backend\models\BaseModel
{

    const TYPE_MANE_JIAN = 1;
    const TYPE_WU_MEN_KAN = 2;
    const TYPE_MANE_ZHEKOU = 3;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%coupon}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'coupon_name', 'restriction', 'coupon_value', 'number', 'max_get_number', 'start_time', 'end_time', 'consume_time', 'invalid_time'], 'required'],
            [['type', 'is_lock', 'is_delete', 'number', 'max_get_number'], 'integer'],
            [['restriction', 'coupon_value'], 'number'],
            [['coupon_name'], 'string', 'max' => 50],
            ['is_lock', 'default', 'value' => 0],
            ['max_get_number', 'check_max_get_number'],
            [['start_time', 'end_time', 'consume_time', 'invalid_time'], 'gtTimeNow'],
            [['end_time', 'invalid_time'], 'gtStartTime'],
            [['start_time', 'end_time', 'consume_time', 'invalid_time'], 'safe']
        ];
    }

    /**
     * @param $attribute
     * @author von
     */
    public function check_max_get_number($attribute)
    {
        if ($this->$attribute > $this->number) {
            $this->addError('number', '发行数量必须大于或等于' . $this->attributeLabels()[$attribute]);
        }
    }

    /**
     * @param $attribute
     * @param $params
     * @author von
     */
    public function gtTimeNow($attribute, $params)
    {
        if ($this->$attribute <= time()) {
            $this->addError($attribute, $this->attributeLabels()[$attribute] . '必须大于当前时间');
        }
    }

    /**
     * @param $attribute
     * @param $params
     * @author von
     */
    public function gtStartTime($attribute, $params)
    {
        if ($attribute == 'end_time') {
            if ($this->$attribute <= $this->start_time) {
                $this->addError($attribute, $this->attributeLabels()[$attribute] . '必须大于开始领取时间');
            }
        }
        if ($attribute == 'invalid_time') {
            if ($this->$attribute <= $this->consume_time) {
                $this->addError($attribute, $this->attributeLabels()[$attribute] . '必须大于开始使用时间');
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => '类别',
            'coupon_name' => '名称',
            'restriction' => '约束限制',
            'coupon_value' => '优惠券值',
            'is_lock' => '是否冻结',
            'is_delete' => 'Is Delete',
            'number' => '发行数量',
            'max_get_number' => '每人限领取数量',
            'start_time' => '开始领取时间',
            'end_time' => '结束领取时间',
            'consume_time' => '使用时间',
            'invalid_time' => '过期时间',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    /**
     * @return array
     */
    public function scenarios()
    {
        return array_merge(parent::scenarios(), [
            'delete' => ['is_delete'],
            'lock' => ['is_lock'],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * 通过id查询数据
     * @param $id
     * @return bool|null|static
     */
    public function findOneById($id)
    {
        $model = self::findOne(['id' => $id]);
        if ($model) {
            return $model;
        }
        return false;
    }

    /**
     * 处理返回数据
     * @return array
     */
    public function getView()
    {
        return [
            'id' => (string)$this->id,
            'type' => $this->type,
            'coupon_name' => $this->coupon_name,
            'restriction' => $this->restriction,
            'coupon_value' => $this->coupon_value,
            'is_lock' => $this->is_lock,
            'number' => $this->number,
            'max_get_number' => $this->max_get_number,
            'spike_rate' => round(count($this->userCoupon) / $this->number,4) ,
            'start_time' => $this->start_time,
            'end_time' => $this->end_time,
            'consume_time' => $this->consume_time,
            'invalid_time' => $this->invalid_time,
            'updated_at' => $this->updated_at,
            'created_at' => $this->created_at,
        ];
    }

    /**
     * 新增优惠券
     * @param $data
     * @return array|bool
     */
    public function createCoupon($data)
    {
        $model = new self();
        $model->attributes = $data;
        $model->start_time = strtotime($model->start_time);
        $model->end_time = strtotime($model->end_time);
        $model->consume_time = strtotime($model->consume_time);
        $model->invalid_time = strtotime($model->invalid_time);
        if ($model->validate() && $model->save()) {
            return true;
        }
        return $model->getErrors();
    }

    /**
     * 处理保存前的数据格式
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->is_delete = self::DELETE_NOT;
            $this->created_at = time();
            $this->updated_at = time();
        } else {
            $this->updated_at = time();
        }

        return parent::beforeSave($insert);
    }

    /**
     * 获取查询sql
     * @param $params
     * @return $this
     */
    public function getQuery($params)
    {
        return $query = self::find()
            ->where(['is_delete' => self::DELETE_NOT])
            ->andFilterWhere(['like', 'coupon_name', $params['coupon_name']])
            ->andFilterWhere(['like', 'restriction', $params['restriction']])
            ->andFilterWhere(['like', 'coupon_value', $params['coupon_value']])
            ->andFilterWhere(['is_lock' => $params['is_lock']])
            ->andFilterWhere(['type' => $params['type']]);
    }

    /**
     * 修改优惠券
     * @param $params
     * @return array|bool
     */
    public function modifyCoupon($params)
    {
        $userCouponModel = UserCoupon::findOne(['coupon_id' => $this->id]);
        if ($userCouponModel) {//发放的优惠券 可以修改哪些字段
            if (!empty($params['type'])) {
                $this->addError('type', '优惠券已发放,优惠券类别不支持修改');
            }
            if (!empty($params['restriction'])) {
                $this->addError('restriction', '优惠券已发放,使用门槛不支持修改');
            }
            if (!empty($params['coupon_value'])) {
                $this->addError('coupon_value', '优惠券已发放,优惠券价值不支持修改');
            }
        }
        if (!empty($this->getErrors())) {
            return $this->getErrors();
        }
        $this->attributes = $params;

        if (!empty($params['start_time'])) {
            $this->start_time = strtotime($params['start_time']);
        }
        if (!empty($params['end_time'])) {
            $this->end_time = strtotime($params['end_time']);
        }
        if (!empty($params['consume_time'])) {
            $this->consume_time = strtotime($params['consume_time']);
        }
        if (!empty($params['invalid_time'])) {
            $this->invalid_time = strtotime($params['invalid_time']);
        }
        if ($this->validate() && $this->save()) {
            return true;
        }
        return $this->getErrors();
    }

    /**
     * 获取数据列
     * @param $params
     * @return array
     */
    public function getList($params)
    {
        $page_size = Param::getHeaders('page_size');
        $page = Param::getHeaders('page');
        $query = self::getQuery($params);
        $models = $query->limit($page_size)
            ->offset(($page - 1) * $page_size)
            ->orderBy('created_at DESC')
            ->all();
        $list = [];
        foreach ($models as $model) {
            $list[] = $model->getView();
        }
        $count = $query->count();
        $param[ConstantHelper::COUNT] = $count;
        $param[ConstantHelper::PAGE] = $page;
        $param[ConstantHelper::PAGE_SIZE] = $page_size;
        $param[ConstantHelper::PAGE_COUNT] = ceil($count / $page_size);
        $param[ConstantHelper::LISTS] = $list;
        return self::backListFormat($param);
    }

    /**
     * 删除优惠券
     * @param $this ->id
     * @return array|bool
     */
    public function del()
    {
        $this->scenario = 'delete';
        $this->is_delete = self::DELETED;
        UserCoupon::updateAll(['is_delete' => self::DELETED], ['coupon_id' => $this->id]);
        if ($this->save()) {
            return true;
        }
        return $this->getErrors();
    }

    /**
     * 冻结或解冻优惠券
     * @param $this ->id
     * @return array|bool
     */
    public function lockCouponById()
    {
        $this->scenario = 'lock';
        if ($this->is_lock === ConstantHelper::IS_LOCK_TRUE) {
            $this->is_lock = ConstantHelper::IS_LOCK_FALSE;
        } else {
            $this->is_lock = ConstantHelper::IS_LOCK_TRUE;
        }
        UserCoupon::updateAll(['is_lock' => $this->is_lock], ['coupon_id' => $this->id]);
        if ($this->save()) {
            return true;
        }
        return $this->getErrors();
    }

    /**
     * @return \yii\db\ActiveQuery
     * @author von
     */
    public function getUserCoupon()
    {
        return $this->hasMany(UserCoupon::className(),['coupon_id'=>'id']);
    }
}
