<?php
/**
 **********************************************************
 * @author : YiChaobao [ yichaobao@163.com ]
 * @time : 2019/01/14 9:57
 * @copyright : (c) 2019 YiChaobao All rights reserved.
 **********************************************************
 * @name : Role.php
 * @description : 用户角色管理
 **/

namespace backend\modules\users\controllers;

use common\base\RController;
use Yii;

class RoleController extends RController
{
    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $service = $this->getService('User.Role');
        return $service->getLists();
    }

    /**
     * @desc: 创建
     * @name: actionCreate
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionCreate()
    {
        $data = Yii::$app->request->post();
        $service = $this->getService('User.Role');
        return $service->addData($data);
    }

    /**
     * @desc: 详情
     * @name: actionView
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionView()
    {
        $id = Yii::$app->request->get('id');
        $service = $this->getService('User.Role');
        return $service->getDataInfo($id);
    }

    /**
     * @desc: 更新
     * @name: actionUpdate
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionUpdate()
    {
        $request = Yii::$app->request;
        $id = $request->get('id');
        $data = $request->post();
        $service = $this->getService('User.Role');
        return $service->updateData($id, $data);
    }

    /**
     * @desc:
     * @name: actionDelete
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionDelete()
    {
        $user_id = Yii::$app->request->get('id');
        $service = $this->getService('User.Role');
        return $service->deleteData($user_id);
    }
}