<?php
/**
 **********************************************************
 * @author : YiChaobao [ yichaobao@163.com ]
 * @time : 2019/01/01 00:00
 * @copyright : (c) 2019 YiChaobao All rights reserved.
 **********************************************************
 * @name : UserController.php
 * @description : 会员控制器
 **/

namespace backend\modules\users\controllers;

use common\base\RController;
use Yii;
use common\helpers\ErrorCode;
use common\helpers\WeHelper;
use yii\helpers\Json;
class UsersController extends RController
{

    public function actions()
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * @desc: 用户列表【包含搜索】
     * @name: actionIndex
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        $page_size = $request->get('page_size',20);//分页数[默认20条]
        $order = $request->get('order','reg_time DESC');//排序方式[默认注册时间倒序]
        $where = [];
        $where['sex'] = $request->get('sex','');//性别
        $where['mobile'] = $request->get('mobile','');//手机号码
        $reg_start_time = $request->get('reg_start_time');
        $where['reg_start_time'] = $reg_start_time ? strtotime($reg_start_time) : null;
        $reg_end_time = $request->get('reg_end_time');
        $where['reg_end_time'] = $reg_end_time ? strtotime($reg_end_time) : null;
        $service = $this->getService('User.User');
        return $service->getUserLists($where,$order,$page_size);
    }

    /**
     * @desc: 创建用户
     * @name: actionCreate
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionCreate()
    {
//        var_dump(ip2long(Yii::$app->request->userIP));
//        die();
        $data = Yii::$app->request->bodyParams;
        $service = $this->getService('User.User');
        return $service->addUser($data);
    }

    /**
     * @desc: 获取用户信息
     * @name: actionView
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionView()
    {
        $user_id = Yii::$app->request->get('id');
        $service = $this->getService('User.User');
        return $service->getUserInfo($user_id);
    }

    /**
     * @desc: 更新用户信息
     * @name: actionUpdate
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionUpdate()
    {
        $request = Yii::$app->request;
        $user_id = $request->get('id');
        $data = $request->post();
        $service = $this->getService('User.User');
        return $service->updateUser($user_id, $data);
    }

    /**
     * @desc: 删除用户信息
     * @name: actionDelete
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionDelete()
    {
        $user_id = Yii::$app->request->get('id');
        $service = $this->getService('User.User');
        return $service->delUser($user_id);
    }

    /**
     * @desc: 锁定会员
     * @name: actionLock
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionLock(){
        $user_id = Yii::$app->request->get('id');
        $service = $this->getService('User.User');
        return $service->setUserLockStatus($user_id,1);
    }

    /**
     * @desc: 解除锁定
     * @name: actionUnlock
     * @return mixed
     * @author：yichaobao [yichaobao@163.com]
     * @version : V1.0.0
     */
    public function actionUnlock(){
        $user_id = Yii::$app->request->get('id');
        $service = $this->getService('User.User');
        return $service->setUserLockStatus($user_id,0);
    }

}